#!/bin/bash
set -e

case "$1" in
    remove)
        echo "Stopping service"
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop linuxtag.service || true
        fi
        ;;

    upgrade | deconfigure | failed-upgrade) ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
